//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsProgramOrganisation.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exams
    {
        public int examId { get; set; }
        public string examName { get; set; }
        public Nullable<System.DateTime> examTime { get; set; }
    }
}
